name: swagger_ui_darto
description: The Swagger UI Darto is a plugin developed exclusively for the Darto framework.
version: 0.0.1
homepage: https://github.com/evandersondev/swagger_ui_darto

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  darto: ^0.0.17
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
